### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by Xa52c** [Chainflow/cosmos-validator-mission-control#11]
git clone git@github.com:Chainflow/cosmos-validator-mission-control.git
Cloning into 'cosmos-validator-mission-control'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by anilCSE** [comment]
Can you try with https. git clone https://github.com/Chainflow/cosmos-validator-mission-control

**Comment by anilCSE** [comment]
@PrathyushaLakkireddy please fix the instructions

**Comment by Xa52c** [comment]
it works! thank you
