### ISSUE TITLE
INSTRUCTIONS.md issues

### ISSUE THREAD

**Issue by Xa52c** [Chainflow/cosmos-validator-mission-control#12]
I've been following INSTRUCTIONS.md and had a few issues.

Firstly, the influxdb and telegraf versions are now out of date so the code cannot be copied / pasted / run.

`Configure the following variables in config.toml`
`External open RPC endpoint(secondary RPC other than your own validator). Useful to gather information like validator caught up, syncing and missed blocks etc.`
`external_rpc=`
default value doesn't work.
on testnet, i have sucessfully tried: http://rpc.gaia.bigdipper.live:26657
on livenet, https://rpc.cosmos.network/

`After populating config.toml, check if you have connected to influxdb.`

how to do that? do we need to run

`CREATE DATABASE vcf`?

next issue

`Grafana Dashboards
Import the dashboards
Select the datasources and click on import.`

which datasource? we did not create any, what should they be?

**Comment by Xa52c** [comment]
i struggled to get telegram notifications working. i needed the info from this link

https://medium.com/@wk0/send-and-receive-messages-with-the-telegram-api-17de9102ab78

to help create a bot, extract the tg_chat_id, and the tg_bot_token.

i haven't figured out how to get Sendgrid working yet.

**Comment by PrathyushaLakkireddy** [comment]
We have updated the instructions doc to download influxdb and telegraf, you can try those.

You have to configure external_rpc, default value is just as an example. 

After running influxdb you can check the status of it bu running command  **sudo -S service influxdb status** _(Please follow the updated instructions doc for installation and to run influxdb and telegraf)_
If the status of influxdb is active then influxdb is running properly. 

To create databases you have to go to influx shell and create database
$ influx
> CREATE DATABASE vcf
> CREATE DATABASE telegraf

To create datasources I have updated the instructions doc, you can take reference of it to create datasource and to import dashboards.

**Comment by PrathyushaLakkireddy** [comment]
> I've been following INSTRUCTIONS.md and had a few issues.
> 
> Firstly, the influxdb and telegraf versions are now out of date so the code cannot be copied / pasted / run.
> 
> `Configure the following variables in config.toml`
> `External open RPC endpoint(secondary RPC other than your own validator). Useful to gather information like validator caught up, syncing and missed blocks etc.`
> `external_rpc=`
> default value doesn't work.
> on testnet, i have sucessfully tried: http://rpc.gaia.bigdipper.live:26657
> on livenet, https://rpc.cosmos.network/
> 
> `After populating config.toml, check if you have connected to influxdb.`
> 
> how to do that? do we need to run
> 
> `CREATE DATABASE vcf`?
> 
> next issue
> 
> `Grafana Dashboards Import the dashboards Select the datasources and click on import.`
> 
> which datasource? we did not create any, what should they be?



We have updated the instructions doc to download influxdb and telegraf, you can try those.

You have to configure external_rpc, default value is just as an example. 

After running influxdb you can check the status of it bu running command  **sudo -S service influxdb status** _(Please follow the updated instructions doc for installation and to run influxdb and telegraf)_
If the status of influxdb is active then influxdb is running properly. 

To create databases you have to go to influx shell and create database
$ influx
> CREATE DATABASE vcf
> CREATE DATABASE telegraf

To create datasources I have updated the instructions doc, you can take reference of it to create datasource and to import dashboards.

**Comment by PrathyushaLakkireddy** [comment]
> i struggled to get telegram notifications working. i needed the info from this link
> 
> https://medium.com/@wk0/send-and-receive-messages-with-the-telegram-api-17de9102ab78
> 
> to help create a bot, extract the tg_chat_id, and the tg_bot_token.
> 
> i haven't figured out how to get Sendgrid working yet.


You can find **BotFather** in telegram. Open that chat and type **/newbot** , and follow the steps to create bot.
To get your tg_chat_id id **What's my id?** go to this account from your telegram and type **/start**, it will give your account ID.  
**tg_bot_token** will be found after creating the bot itself you can just use that.

To get sendgrid token you have to create an account in sendgrid and can use the token to get mails.
